# Generated by Django 3.2.4 on 2021-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuspayment',
            name='account_no',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cuspayment',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='cuspayment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cuspayment',
            name='cash',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuspayment',
            name='check_date',
            field=models.CharField(blank=True, default='', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='cuspayment',
            name='check_no',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cuspayment',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cuspayment',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cuspayment',
            name='upi',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
