# Generated by Django 3.2.4 on 2021-07-11 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outward_purchase', '0001_initial'),
        ('customerpay', '0002_auto_20210701_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuspayment',
            name='bills',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='outward_purchase.outward_purchase'),
        ),
        migrations.AddField(
            model_name='cuspayment',
            name='dates',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
