# Generated by Django 3.2.4 on 2021-07-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerpay', '0003_auto_20210711_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuspayment',
            name='cus',
        ),
    ]
