# Generated by Django 3.2.4 on 2021-07-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodoutward', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodoutward',
            old_name='discounts',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='prodoutward',
            old_name='gsts',
            new_name='gst',
        ),
        migrations.RenameField(
            model_name='prodoutward',
            old_name='prices',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='prodoutward',
            old_name='prods',
            new_name='prod',
        ),
        migrations.RenameField(
            model_name='prodoutward',
            old_name='rates',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='prodoutward',
            name='quan',
        ),
        migrations.AddField(
            model_name='prodoutward',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodoutward',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
