# Generated by Django 3.2.4 on 2021-07-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodoutward', '0002_auto_20210710_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodoutward',
            name='discount',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prodoutward',
            name='gst',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
