# Generated by Django 3.2.4 on 2021-07-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodinward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('rate', models.FloatField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('discount', models.FloatField(blank=True, max_length=100, null=True)),
                ('gst', models.FloatField(blank=True, max_length=100, null=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
            ],
        ),
    ]
