# Generated by Django 3.2.4 on 2021-07-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodinward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodinward',
            name='is_biiled',
            field=models.BooleanField(default=False),
        ),
    ]
