# Generated by Django 3.2.4 on 2021-07-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodinward', '0002_prodinward_is_biiled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodinward',
            old_name='is_biiled',
            new_name='is_billed',
        ),
    ]
