# Generated by Django 3.2.4 on 2021-07-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodinward', '0003_rename_is_biiled_prodinward_is_billed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodinward',
            name='quantity',
            field=models.IntegerField(max_length=100),
        ),
    ]
