# Generated by Django 3.2.4 on 2021-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodinward', '0005_alter_prodinward_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodinward',
            name='discount',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prodinward',
            name='gst',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
