# Generated by Django 3.2.4 on 2021-07-10 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0005_alter_customer_photo'),
        ('prodoutward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='outward_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('total', models.IntegerField()),
                ('gst', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer.customer')),
                ('products', models.ManyToManyField(related_name='outward_purchase_bill', to='prodoutward.prodoutward')),
            ],
        ),
    ]
