# Generated by Django 3.2.4 on 2021-07-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outward_purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outward_purchase',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='outward_purchase',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
