# Generated by Django 3.2.4 on 2021-07-11 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inward_purchase', '0001_initial'),
        ('supplierpay', '0002_auto_20210701_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppayment',
            name='bill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inward_bill', to='inward_purchase.inward_purchase'),
        ),
        migrations.AddField(
            model_name='suppayment',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
