# Generated by Django 3.2.4 on 2021-07-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpay', '0003_auto_20210711_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppayment',
            name='bill',
        ),
    ]
