# Generated by Django 3.2.4 on 2021-07-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inward_purchase', '0001_initial'),
        ('supplierpay', '0004_remove_suppayment_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppayment',
            name='bill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inward_bill', to='inward_purchase.inward_purchase'),
        ),
    ]
