# Generated by Django 3.2.4 on 2021-07-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inward_purchase', '0001_initial'),
        ('supplierpay', '0005_suppayment_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppayment',
            name='date',
        ),
        migrations.AlterField(
            model_name='suppayment',
            name='bill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='inward_purchase.inward_purchase'),
        ),
    ]
