# Generated by Django 3.2.4 on 2021-07-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierpay', '0008_auto_20210711_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppayment',
            name='sup',
        ),
    ]
